export type LearnArticle = {
  href: string;
  emoji: string;
  title: string;
  desc: string;
  tag: string;
  tagColor: string;
  minutes: string;
};

export const LEARN_ARTICLES: LearnArticle[] = [
  {
    href: "/learn/us-stock-basics",
    emoji: "🇺🇸",
    title: "미국주식 투자 완전 입문 가이드",
    desc: "계좌 개설, 수수료·환율, 세금 개념, DCA, Investus 5분 루틴까지.",
    tag: "입문",
    tagColor: "#10b981",
    minutes: "18분",
  },
  {
    href: "/learn/value-investing",
    emoji: "🧙",
    title: "가치투자·대가 전략 가이드",
    desc: "버핏·그레이엄·린치·보글·달리오·막스 등 전설적 투자가의 핵심 원칙을 한국 투자자 눈높이로 정리.",
    tag: "철학",
    tagColor: "#d4af37",
    minutes: "17분",
  },
  {
    href: "/learn/etf",
    emoji: "📦",
    title: "미국 ETF 완전 가이드 — SPY·VOO·QQQ",
    desc: "운용보수·추적오차, 레버리지 함정, 코어/위성 나누는 법.",
    tag: "ETF",
    tagColor: "#60a5fa",
    minutes: "18분",
  },
  {
    href: "/learn/sp500",
    emoji: "📈",
    title: "S&P500 완전 가이드",
    desc: "미국 대형주 500개 지수의 구성, 역사적 성과, 투자 전략.",
    tag: "지수",
    tagColor: "#60a5fa",
    minutes: "16분",
  },
  {
    href: "/learn/nasdaq",
    emoji: "💻",
    title: "나스닥 완전 가이드 — 나스닥100과 QQQ",
    desc: "거래소·종합지수·나스닥100 구분, S&P500과의 차이.",
    tag: "지수",
    tagColor: "#38bdf8",
    minutes: "16분",
  },
  {
    href: "/learn/valuation",
    emoji: "🔢",
    title: "PER·PBR·기업 가치 평가 가이드",
    desc: "주식이 비싼지 싼지 판단하는 밸류에이션 지표와 EV/EBITDA.",
    tag: "분석",
    tagColor: "#c084fc",
    minutes: "16분",
  },
  {
    href: "/learn/financial-statements",
    emoji: "📋",
    title: "재무제표 읽기 — 손익·재무·현금흐름",
    desc: "10-K·10-Q에서 매출·이익·부채·FCF를 어떻게 보는지.",
    tag: "분석",
    tagColor: "#a78bfa",
    minutes: "17분",
  },
  {
    href: "/learn/dividend",
    emoji: "💰",
    title: "배당 투자 가이드",
    desc: "배당수익률, 배당귀족, DRIP, 미국주식 배당 세금.",
    tag: "수익",
    tagColor: "#10b981",
    minutes: "15분",
  },
  {
    href: "/learn/bonds",
    emoji: "📜",
    title: "채권과 금리 — 10년물·역수익률",
    desc: "채권 가격과 금리의 역관계, 주식과의 역할, 대표 ETF.",
    tag: "매크로",
    tagColor: "#94a3b8",
    minutes: "16분",
  },
  {
    href: "/learn/macro-rates",
    emoji: "🏛️",
    title: "CPI·연준(FOMC)·금리 가이드",
    desc: "인플레이션 지표, 금리 결정이 주식·채권에 미치는 영향.",
    tag: "매크로",
    tagColor: "#f59e0b",
    minutes: "16분",
  },
  {
    href: "/learn/futures",
    emoji: "📆",
    title: "선물·프리마켓 읽는 법",
    desc: "나스닥·S&P 선물, 야간 거래, 장 시작 전 시장 온도.",
    tag: "시장",
    tagColor: "#38bdf8",
    minutes: "14분",
  },
  {
    href: "/learn/dca",
    emoji: "📅",
    title: "적립식 투자(DCA) 가이드",
    desc: "매달 같은 금액, 환율 분산, 실패하는 적립 패턴.",
    tag: "습관",
    tagColor: "#10b981",
    minutes: "16분",
  },
  {
    href: "/learn/compound",
    emoji: "📈",
    title: "복리와 장기 투자",
    desc: "시간이 수익을 만드는 원리, 초기·중기·후기의 차이.",
    tag: "원리",
    tagColor: "#10b981",
    minutes: "14분",
  },
  {
    href: "/learn/investing-psychology",
    emoji: "🧠",
    title: "투자 심리·행동재무 가이드",
    desc: "FOMO, 손실 회피, 공포탐욕, 규칙으로 막는 실수.",
    tag: "심리",
    tagColor: "#f59e0b",
    minutes: "15분",
  },
  {
    href: "/learn/us-stock-tax",
    emoji: "🧾",
    title: "한국 거주자 미국주식 세금·계좌",
    desc: "양도소득·배당 원천징수·종합과세 개념 (세무 자문 아님).",
    tag: "세금",
    tagColor: "#f87171",
    minutes: "18분",
  },
  {
    href: "/learn/usd-krw",
    emoji: "💱",
    title: "환율과 미국주식",
    desc: "달러 vs 원화 수익률, 환헤지 vs 환노출.",
    tag: "환율",
    tagColor: "#f59e0b",
    minutes: "15분",
  },
  {
    href: "/learn/sectors",
    emoji: "🏭",
    title: "미국 주식 11개 섹터 가이드",
    desc: "GICS 섹터별 특징, 기술주 쏠림 피하기.",
    tag: "섹터",
    tagColor: "#fb923c",
    minutes: "17분",
  },
  {
    href: "/learn/fear-greed",
    emoji: "😱",
    title: "공포탐욕지수 완전 가이드",
    desc: "CNN 공포·탐욕 지수 계산법과 활용 한계.",
    tag: "심리",
    tagColor: "#f59e0b",
    minutes: "14분",
  },
  {
    href: "/learn/buffett-indicator",
    emoji: "🏦",
    title: "버핏지수 완전 가이드",
    desc: "시가총액/GDP, 고평가·저평가 맥락 읽기.",
    tag: "밸류",
    tagColor: "#c084fc",
    minutes: "14분",
  },
  {
    href: "/learn/portfolio-strategy",
    emoji: "💼",
    title: "포트폴리오 분산·리밸런싱 전략",
    desc: "비중·현금·섹터·리밸런싱 주기.",
    tag: "전략",
    tagColor: "#fb923c",
    minutes: "16분",
  },
];
