export type LearnArticle = {
  href: string;
  emoji: string;
  title: string;
  desc: string;
  tag: string;
  tagColor: string;
  minutes: string;
  /** Optional series for hub grouping */
  series?: "입문 7일" | "세금·계좌" | "매크로" | "분석·전략" | "자산·상품" | "시장별";
};

export const LEARN_SERIES: { id: NonNullable<LearnArticle["series"]>; title: string; blurb: string }[] = [
  { id: "입문 7일", title: "입문 로드맵", blurb: "처음이라면 이 순서로" },
  { id: "시장별", title: "시장별 가이드", blurb: "한국·안전자산·부동산" },
  { id: "세금·계좌", title: "세금·계좌", blurb: "세후 수익률을 좌우" },
  { id: "매크로", title: "매크로·시장", blurb: "금리·지표·캘린더" },
  { id: "분석·전략", title: "분석·전략", blurb: "숫자·철학·체크리스트" },
  { id: "자산·상품", title: "자산·상품", blurb: "ETF·리츠·크립토·옵션" },
];

export const LEARN_ARTICLES: LearnArticle[] = [
  {
    href: "/learn/us-stock-basics",
    emoji: "🇺🇸",
    title: "미국주식 투자 완전 입문 가이드",
    desc: "계좌 개설, 수수료·환율, 세금 개념, DCA, Investus 5분 루틴까지.",
    tag: "입문",
    tagColor: "#10b981",
    minutes: "22분",
    series: "입문 7일",
  },
  {
    href: "/learn/korea-stocks",
    emoji: "🇰🇷",
    title: "한국주식 투자 입문 가이드",
    desc: "코스피·시총상위·수급·장전·장중·장후, 미국주식과의 차이.",
    tag: "한국",
    tagColor: "#10b981",
    minutes: "22분",
    series: "시장별",
  },
  {
    href: "/learn/safe-assets",
    emoji: "🛡️",
    title: "안전자산 가이드 — 비트코인·이더·금·은",
    desc: "가상화폐와 현물을 나눠 보기, 금리·달러·ETF 수급, 비중.",
    tag: "안전자산",
    tagColor: "#a78bfa",
    minutes: "24분",
    series: "시장별",
  },
  {
    href: "/learn/safe-haven-etfs",
    emoji: "💵",
    title: "안전자산 탑10 — 달러·TLT·GLD·SGOV 해설",
    desc: "히트맵 달러인덱스·국채·금 ETF 10개가 뭔지, 만기·금리 민감도 한 장.",
    tag: "안전자산",
    tagColor: "#a78bfa",
    minutes: "12분",
    series: "시장별",
  },
  {
    href: "/learn/korea-real-estate",
    emoji: "🏠",
    title: "한국 부동산 입문 — 매매·전세·정책",
    desc: "공급·전세·대출·세제 삼각 축, 실수요 vs 투자 수요.",
    tag: "부동산",
    tagColor: "#34d399",
    minutes: "22분",
    series: "시장별",
  },
  {
    href: "/learn/myths",
    emoji: "🚫",
    title: "초보 투자 오해 TOP10",
    desc: "레버리지, 타이밍, 대가 복제, 세금 등 흔한 오해.",
    tag: "입문",
    tagColor: "#f87171",
    minutes: "26분",
    series: "입문 7일",
  },
  {
    href: "/learn/buy-checklist",
    emoji: "✅",
    title: "매수 전 체크리스트 10가지",
    desc: "비중·밸류·세금·심리 — 사기 전에 적을 규칙.",
    tag: "습관",
    tagColor: "#10b981",
    minutes: "20분",
    series: "입문 7일",
  },
  {
    href: "/learn/dca",
    emoji: "📅",
    title: "적립식 투자(DCA) 가이드",
    desc: "매달 같은 금액, 환율 분산, 실패하는 적립 패턴.",
    tag: "습관",
    tagColor: "#10b981",
    minutes: "22분",
    series: "입문 7일",
  },
  {
    href: "/learn/compound",
    emoji: "📈",
    title: "복리와 장기 투자",
    desc: "시간이 수익을 만드는 원리, 초기·중기·후기의 차이.",
    tag: "원리",
    tagColor: "#10b981",
    minutes: "24분",
    series: "입문 7일",
  },
  {
    href: "/learn/investing-psychology",
    emoji: "🧠",
    title: "투자 심리·행동재무 가이드",
    desc: "FOMO, 손실 회피, 공포탐욕, 규칙으로 막는 실수.",
    tag: "심리",
    tagColor: "#f59e0b",
    minutes: "22분",
    series: "입문 7일",
  },
  {
    href: "/learn/portfolio-strategy",
    emoji: "💼",
    title: "포트폴리오 분산·리밸런싱 전략",
    desc: "비중·현금·섹터·리밸런싱 주기.",
    tag: "전략",
    tagColor: "#fb923c",
    minutes: "20분",
    series: "입문 7일",
  },
  {
    href: "/learn/value-investing",
    emoji: "🧙",
    title: "가치투자·대가 전략 가이드",
    desc: "버핏·그레이엄·린치·보글·달리오·막스 등 전설적 투자가의 핵심 원칙.",
    tag: "철학",
    tagColor: "#d4af37",
    minutes: "24분",
    series: "분석·전략",
  },
  {
    href: "/learn/etf",
    emoji: "📦",
    title: "미국 ETF 완전 가이드 — SPY·VOO·QQQ",
    desc: "운용보수·추적오차, 레버리지 함정, 코어/위성 나누는 법.",
    tag: "ETF",
    tagColor: "#60a5fa",
    minutes: "20분",
    series: "자산·상품",
  },
  {
    href: "/learn/kr-us-etf",
    emoji: "🇰🇷",
    title: "한국 vs 미국 ETF — KODEX·TIGER vs SPY",
    desc: "국내 상장 해외 ETF와 미국 ETF, 세금·환율·환헤지 차이.",
    tag: "ETF",
    tagColor: "#10b981",
    minutes: "23분",
    series: "자산·상품",
  },
  {
    href: "/learn/reits",
    emoji: "🏢",
    title: "REITs 부동산 ETF 가이드",
    desc: "리츠 구조, 금리·임대수익, VNQ·IYR, 포트폴리오 역할.",
    tag: "자산",
    tagColor: "#60a5fa",
    minutes: "22분",
    series: "자산·상품",
  },
  {
    href: "/learn/options",
    emoji: "📉",
    title: "옵션 기초 — 콜·풋·IV",
    desc: "콜·풋, 행사가·만기, 내재변동성. 교육용·고위험 안내.",
    tag: "파생",
    tagColor: "#a855f7",
    minutes: "22분",
    series: "자산·상품",
  },
  {
    href: "/learn/technical-analysis",
    emoji: "📊",
    title: "기술적 분석 입문 — 이동평균·RSI",
    desc: "이동평균, RSI, 지지·저항. 차트는 보조 도구로.",
    tag: "차트",
    tagColor: "#38bdf8",
    minutes: "22분",
    series: "분석·전략",
  },
  {
    href: "/learn/sp500",
    emoji: "📈",
    title: "S&P500 완전 가이드",
    desc: "미국 대형주 500개 지수의 구성, 역사적 성과, 투자 전략.",
    tag: "지수",
    tagColor: "#60a5fa",
    minutes: "20분",
    series: "자산·상품",
  },
  {
    href: "/learn/nasdaq",
    emoji: "💻",
    title: "나스닥 완전 가이드 — 나스닥100과 QQQ",
    desc: "거래소·종합지수·나스닥100 구분, S&P500과의 차이.",
    tag: "지수",
    tagColor: "#38bdf8",
    minutes: "22분",
    series: "자산·상품",
  },
  {
    href: "/learn/valuation",
    emoji: "🔢",
    title: "PER·PBR·기업 가치 평가 가이드",
    desc: "주식이 비싼지 싼지 판단하는 밸류에이션 지표와 EV/EBITDA.",
    tag: "분석",
    tagColor: "#c084fc",
    minutes: "22분",
    series: "분석·전략",
  },
  {
    href: "/learn/financial-statements",
    emoji: "📋",
    title: "재무제표 읽기 — 손익·재무·현금흐름",
    desc: "10-K·10-Q에서 매출·이익·부채·FCF를 어떻게 보는지.",
    tag: "분석",
    tagColor: "#a78bfa",
    minutes: "23분",
    series: "분석·전략",
  },
  {
    href: "/learn/earnings-season",
    emoji: "📢",
    title: "실적 시즌 읽는 법",
    desc: "EPS·컨센서스·가이던스, 발표 전후 체크리스트.",
    tag: "시장",
    tagColor: "#c084fc",
    minutes: "22분",
    series: "분석·전략",
  },
  {
    href: "/learn/13f-guide",
    emoji: "🏛️",
    title: "13F·기관 포트폴리오 읽는 법",
    desc: "SEC 13F 공시 해석과 한계. 단순 모방의 위험.",
    tag: "기관",
    tagColor: "#d4af37",
    minutes: "24분",
    series: "분석·전략",
  },
  {
    href: "/learn/dividend",
    emoji: "💰",
    title: "배당 투자 가이드",
    desc: "배당수익률, 배당귀족, DRIP, 미국주식 배당 세금.",
    tag: "수익",
    tagColor: "#10b981",
    minutes: "24분",
    series: "자산·상품",
  },
  {
    href: "/learn/bonds",
    emoji: "📜",
    title: "채권과 금리 — 10년물·역수익률",
    desc: "채권 가격과 금리의 역관계, 주식과의 역할, 대표 ETF.",
    tag: "매크로",
    tagColor: "#94a3b8",
    minutes: "22분",
    series: "매크로",
  },
  {
    href: "/learn/commodities",
    emoji: "🛢️",
    title: "원자재 투자 가이드 — 금·유가·농산물",
    desc: "금, 원유, 농산물·산업금속, GLD·DBC 등 ETF와 인플레 헤지.",
    tag: "자산",
    tagColor: "#fbbf24",
    minutes: "22분",
    series: "자산·상품",
  },
  {
    href: "/learn/crypto",
    emoji: "₿",
    title: "비트코인·암호화폐 가이드",
    desc: "BTC·ETH, 현물 ETF(IBIT·FBTC), COIN·MSTR, 변동성·비중.",
    tag: "자산",
    tagColor: "#f97316",
    minutes: "22분",
    series: "자산·상품",
  },
  {
    href: "/learn/macro-rates",
    emoji: "🏛️",
    title: "CPI·연준(FOMC)·금리 가이드",
    desc: "인플레이션 지표, 금리 결정이 주식·채권에 미치는 영향.",
    tag: "매크로",
    tagColor: "#f59e0b",
    minutes: "22분",
    series: "매크로",
  },
  {
    href: "/learn/economic-calendar",
    emoji: "🗓️",
    title: "경제 캘린더 활용법",
    desc: "CPI·FOMC·고용 발표 전후 변동성 관리.",
    tag: "매크로",
    tagColor: "#f59e0b",
    minutes: "24분",
    series: "매크로",
  },
  {
    href: "/learn/futures",
    emoji: "📆",
    title: "선물·프리마켓 읽는 법",
    desc: "나스닥·S&P 선물, 야간 거래, 장 시작 전 시장 온도.",
    tag: "시장",
    tagColor: "#38bdf8",
    minutes: "22분",
    series: "매크로",
  },
  {
    href: "/learn/us-stock-tax",
    emoji: "🧾",
    title: "한국 거주자 미국주식 세금·계좌",
    desc: "양도소득·배당 원천징수·종합과세 개념 (세무 자문 아님).",
    tag: "세금",
    tagColor: "#f87171",
    minutes: "24분",
    series: "세금·계좌",
  },
  {
    href: "/learn/korea-accounts",
    emoji: "🏦",
    title: "ISA·연금저축·IRP 가이드",
    desc: "한국 세제혜택 계좌와 미국 ETF·주식, 비과세·세액공제 개념.",
    tag: "세금",
    tagColor: "#f87171",
    minutes: "24분",
    series: "세금·계좌",
  },
  {
    href: "/learn/usd-krw",
    emoji: "💱",
    title: "환율과 미국주식",
    desc: "달러 vs 원화 수익률, 환헤지 vs 환노출.",
    tag: "환율",
    tagColor: "#f59e0b",
    minutes: "22분",
    series: "세금·계좌",
  },
  {
    href: "/learn/sectors",
    emoji: "🏭",
    title: "미국 주식 11개 섹터 가이드",
    desc: "GICS 섹터별 특징, 기술주 쏠림 피하기.",
    tag: "섹터",
    tagColor: "#fb923c",
    minutes: "24분",
    series: "분석·전략",
  },
  {
    href: "/learn/fear-greed",
    emoji: "😱",
    title: "공포탐욕지수 완전 가이드",
    desc: "CNN 공포·탐욕 지수 계산법과 활용 한계.",
    tag: "심리",
    tagColor: "#f59e0b",
    minutes: "20분",
    series: "매크로",
  },
  {
    href: "/learn/buffett-indicator",
    emoji: "🏦",
    title: "버핏지수 완전 가이드",
    desc: "시가총액/GDP, 고평가·저평가 맥락 읽기.",
    tag: "밸류",
    tagColor: "#c084fc",
    minutes: "18분",
    series: "분석·전략",
  },
];
