/**
 * 아카이브된 리포트 (3일 이후 reports.ts에서 이동)
 * 표시에는 사용되지 않으나 콘텐츠 보존용으로 유지합니다.
 */

import type { Report } from "./reports";

export const ARCHIVED_REPORTS: Report[] = [

  // ══════════════════════════════════════════════════════════════════════════
  // 2026-05-13 리포트 (archived 2026-05-15)
  // ══════════════════════════════════════════════════════════════════════════

  {
    id:            "seed-001",
    title:         "트럼프 방중 — 머스크·젠슨황만 에어포스원 탑승, $1조 투자 딜 임박",
    summary:       "트럼프 대통령의 중국 방문에서 일론 머스크(테슬라)·젠슨 황(NVIDIA)이 에어포스원 탑승 유일한 CEO로 확인됐습니다. 현지에서 미중 간 '역대급 경제 합의' 발표 임박 신호가 나오고 있으며, 중국 측 $1조 대미 투자 등 관세 완화 패키지 협상 중이라는 보도가 나왔습니다.",
    body:          "■ 에어포스원 탑승 CEO (2명만 확인)\n\n• 일론 머스크 (테슬라·스페이스X)\n• 젠슨 황 (NVIDIA)\n→ AI 반도체·전기차가 협상 핵심 어젠다임을 시사\n\n■ 전체 CEO 방중 대표단\n\n• 팀 쿡 (Apple) — $3.2T\n• 제이미 다이먼 (JPMorgan) — $765B\n• 마크 저커버그 (Meta) — $863B\n• 래리 핑크 (BlackRock)\n• 스티븐 슈워츠먼 (Blackstone)\n• 데이비드 솔로몬 (Goldman Sachs)\n• 60명+ CEO 동행 → 단순 외교 방문 아닌 '역대급 딜' 신호\n\n■ 시장이 주목하는 합의 항목\n\n• 새로운 미중 경제 협정 체결\n• 중국의 대미 투자 $1조+ 약속\n• 관세 완화 패키지 (트럼프 145% → 협상 타결 시 인하)\n• 농산물·에너지 구매 확대\n• 지정학 리스크 완화 (대만 긴장 일부 해소)\n\n■ 종목별 시사점\n\n1) TSLA: 중국 FSD 규제 완화 협의 → 중국 매출 반등 기대\n2) NVDA: H20 이상급 대중 수출 허가 완화 가능성 주목\n3) AAPL: 중국 AI 기능 개방 협의, 아이폰 판매 회복 기대\n4) 농산물·LNG: 중국 대규모 구매 합의 시 ADM·LNG 종목 수혜\n\n■ 결론\n\n\"There was a reason 60 CEOs went on this trip and that is a MAJOR trade deal.\" — Per Jefferies. 60명 CEO 방중은 역대급 딜의 증거입니다. AI 반도체·전기차·에너지 모두 촉매 역할을 할 수 있습니다.",
    category:      "매크로",
    categoryColor: "purple",
    subject:       "🇺🇸 트럼프 방중 (미중무역)",
    date:          "2026-05-13",
    updatedAt:     "2026.05.14 07:26",
    isPinned:      true,
    images:        ["/charts/trump-china-trade.svg"],
  },
  {
    id:            "seed-002",
    title:         "4월 CPI 쇼크 — 헤드라인 +3.8% 예상 상회, 금리 인하 시계 후퇴",
    summary:       "4월 소비자물가지수(CPI)가 예상을 상회했습니다. 헤드라인 CPI +3.8%(예상 +3.6%), 근원 CPI +2.8%(예상 +2.6%) — 2023년 5월 이후 최고 헤드라인, 2025년 9월 이후 최고 근원 수치입니다.",
    body:          "■ 4월 CPI 실제 데이터\n\n• 헤드라인 CPI: +3.8% (예상 +3.6%) → 예상 상회 ⚠️\n• 근원 CPI (식품·에너지 제외): +2.8% (예상 +2.6%) → 예상 상회 ⚠️\n• 에너지: 전체 물가 상승분의 40% 이상 차지\n\n■ 연준(Fed) 금리 경로 재조정\n\n• 기존 시장 기대(7·9월 인하) → 후퇴\n• CME FedWatch 연내 인하 확률 급감\n• 연준 \"데이터 의존\" 기조 유지\n\n■ 자산별 대응 전략\n\n1) 채권: 장기물 TLT 단기 역풍, 단기물(SHY·BIL) 선호\n2) 성장주: 밸류에이션 압박 — 금리 민감 성장주 주의\n3) 에너지주: 물가 상승 수혜 — XLE, OXY 주목\n4) 달러: 강세 유지 가능성\n\n■ 결론\n\n에너지·원자재 비중을 점검하고, 금리 인하 기대보다는 인플레 지속 가능성을 열어두세요.",
    category:      "매크로",
    categoryColor: "purple",
    subject:       "📈 CPI (인플레·금리)",
    date:          "2026-05-13",
    updatedAt:     "2026.05.13 22:00",
    images:        ["/charts/cpi-shock.svg"],
  },
  {
    id:            "seed-003",
    title:         "NVIDIA — 젠슨 황, 삼성·TSMC·마이크론 공급망 동맹 확대 선언",
    summary:       "NVIDIA CEO 젠슨 황이 삼성, TSMC, 마이크론 등 공급망 파트너에 감사를 표하며 '가능한 한 빠르게 확장하겠다'고 밝혔습니다. AI 인프라 수요 폭증에 대응한 생산 능력 확충 의지를 재확인했습니다.",
    body:          "■ 발언 요지\n\n\"우리는 삼성, TSMC, 마이크론을 비롯한 파트너들에게 매우 감사하다. 가능한 한 빠르게 그들과 함께 확장하고자 한다.\"\n\n■ 공급망 파트너별 분석\n\n• TSMC: Blackwell GPU CoWoS 패키징 핵심 파트너\n• 삼성전자: HBM 메모리 및 패키징 협력 확대 기대\n• 마이크론: HBM3E 공급 확대 — SK하이닉스와 경쟁\n\n■ 한국 기업 수혜\n\n• SK하이닉스: HBM3E 독점 공급 유지, 수혜 최대\n• 삼성전자: HBM 퀄 테스트 통과 후 비중 확대 기대\n\n■ 결론\n\nAI 인프라 투자 사이클 2027년까지 지속. NVIDIA + 삼성전자·SK하이닉스·SOXX ETF 주목.",
    category:      "종목분석",
    categoryColor: "blue",
    subject:       "🟢 NVIDIA (AI반도체)",
    date:          "2026-05-13",
    updatedAt:     "2026.05.13 22:00",
    images:        ["/charts/nvda-supply.svg"],
  },
  {
    id:            "seed-004",
    title:         "Tesla Terrafab × TSMC — 반도체 자립화 전략과 투자 시사점",
    summary:       "테슬라가 자체 반도체 생산 시설 'Terrafab'을 공식 발표했습니다. TSMC는 애리조나 팹에 $20B를 추가 투자하며 테슬라·스페이스X의 공식 칩 파트너로 나섭니다.",
    body:          "■ Terrafab 핵심 내용\n\n테슬라·스페이스X 필요 칩을 자체 공급망으로 충당하는 장기 전략.\n\n■ TSMC 투자 내용\n\n• 애리조나 팹 추가 투자: $20B\n• 미래 팹 추가 배정: $2.5B\n• 테슬라·스페이스X 공식 파트너 예정\n\n■ NVIDIA 플레이북 비교\n\n머스크가 NVIDIA 전략을 그대로 따르는 중:\n1) 배터리 셀 컨소시엄 → 자체 셀 생산\n2) 자체 AI 칩 (Dojo, HW5) 설계\n3) Terrafab으로 생산 내재화\n\n■ 결론\n\nTerrafab × TSMC 협력은 테슬라가 AI·에너지·로보틱스 복합 플랫폼으로 재평가받는 전환점입니다.",
    category:      "종목분석",
    categoryColor: "blue",
    subject:       "🏎️ 테슬라 (AI·반도체)",
    date:          "2026-05-13",
    updatedAt:     "2026.05.13 22:00",
    images:        ["/charts/tesla-terrafab.svg"],
  },
  {
    id:            "seed-005",
    title:         "Google × SpaceX × Anthropic — 우주·AI 삼각 동맹의 투자 시사점",
    summary:       "구글이 SpaceX 지분 7%, Anthropic 지분 15%를 보유하며 우주·AI 생태계 허브로 부상. 이 삼각 동맹은 다음 10년 인프라 투자 사이클의 핵심 축입니다.",
    body:          "■ 삼각 동맹 구조\n\n구글 → SpaceX (지분 7%): 저궤도 위성·우주 인프라\n구글 → Anthropic (지분 15%): Claude AI·기업용 AI 솔루션\nSpaceX → 구글: 스타링크 기반 클라우드 연결성\n\n■ 시너지 포인트\n\n• 구글: 우주 인프라 + AI 모델 동시 확보\n• SpaceX: 구글 클라우드 데이터 위성 전송 수익화\n• Anthropic: 구글 TPU 학습 비용 절감 + 엔터프라이즈 판로\n\n■ 투자 접근법\n\nSpaceX·Anthropic은 비상장. GOOGL을 통한 간접 투자.\n• GOOGL: 클라우드(GCP) + AI + 우주 시너지 수혜\n\n■ 결론\n\n구글은 광고·검색을 넘어 우주·AI 인프라 플랫폼으로 재평가 시점입니다.",
    category:      "섹터",
    categoryColor: "orange",
    subject:       "🌐 구글·SpaceX·Anthropic (우주·AI)",
    date:          "2026-05-13",
    updatedAt:     "2026.05.13 22:00",
    images:        ["/charts/google-spacex.svg"],
  },
  {
    id:            "seed-006",
    title:         "Rocket Lab 주목 — SpaceX 자율기술 해자와 소형 위성 발사 수혜",
    summary:       "SpaceX Falcon 9은 결정론적 알고리즘으로 400회+ 자율 귀환 성공. 발사 비용 경쟁사 대비 60~70% 저렴. SpaceX 비상장 제약 속 소형 위성 발사 대안 RKLB 주목.",
    body:          "■ Falcon 9 자율 시스템\n\n• 결정론적(deterministic) 알고리즘 — AI 머신러닝 아님\n• 400회 이상 부스터 귀환 성공\n• Falcon 9 발사 비용: ~$6,700만 (경쟁사 대비 60~70% 저렴)\n\n■ Rocket Lab (RKLB)\n\n• Electron 로켓: 소형 위성 전용, 100kg 이하 탑재\n• Neutron 로켓: 중형급 시장 진입 개발 중\n• 우주 부품 사업(Space Systems) 고성장 중\n\n■ 결론\n\nSpaceX 기술 해자는 5~10년간 복제 불가. 비상장 제약 속 RKLB가 우주 투자의 현실적 대안입니다.",
    category:      "섹터",
    categoryColor: "orange",
    subject:       "🚀 SpaceX·Rocket Lab (우주)",
    date:          "2026-05-13",
    updatedAt:     "2026.05.13 22:00",
    images:        ["/charts/rocketlab.svg"],
  },
  {
    id:            "seed-007",
    title:         "테슬라 FSD — 자율주행이 바꾸는 삶, 구독 수익화의 진짜 시작",
    summary:       "팔·다리 없이 태어난 John Z가 테슬라 FSD로 처음 독립적 이동이 가능해졌습니다. 구독 수익화·라이선싱 모델이 테슬라의 다음 성장 동력임을 보여주는 상징적 사례입니다.",
    body:          "■ FSD 접근성 사례\n\nJohn Z: 팔·다리 없이 태어난 사용자. 테슬라 Model Y + FSD로 처음 완전한 이동의 자유.\n\"가속 페달을 밟을 수 없는 나에게 FSD는 삶의 확장이다.\"\n\n■ FSD 구독 모델 현황\n\n• FSD 월정액: $99/월\n• 누적 활성 사용자: ~60만 명 (2026 Q1)\n• 자율주행 누적 마일리지: 30억 마일+ 돌파\n\n■ 라이선싱 수익 모델\n\n• 현대차·GM 등과 협의 보도\n• 계약 1건 = 연간 수억 달러 수익 가능\n\n■ 결론\n\nFSD는 구독·라이선싱 네 가지 레이어를 가진 복합 사업. 테슬라 밸류에이션에서 FSD 소프트웨어 가치 반영 시점이 다가오고 있습니다.",
    category:      "종목분석",
    categoryColor: "blue",
    subject:       "🏎️ 테슬라 (FSD·자율주행)",
    date:          "2026-05-13",
    updatedAt:     "2026.05.13 22:00",
    images:        ["/charts/tesla-fsd.svg"],
  },
  {
    id:            "seed-008",
    title:         "애플 AirPods Pro — 카메라 탑재, Siri AI 비서 완전체 전환 시작",
    summary:       "애플이 카메라를 내장한 신형 AirPods 개발에 착수했습니다. 카메라가 Siri에 시각 정보를 제공하고 주변 환경을 인식해 맥락 기반 AI 응답을 제공하게 됩니다.",
    body:          "■ 핵심 내용\n\n• 각 이어버드에 소형 카메라 탑재\n• 카메라로 Siri에 시각 정보 실시간 제공\n• 사진·영상 촬영은 불가 — AI 맥락 인식 전용\n• 캡처 데이터는 로컬 처리 (프라이버시)\n\n■ 투자 시사점\n\n1) 애플 생태계 락인 강화\n2) 온디바이스 AI 반도체 수요 증가 → TSMC·SK하이닉스 수혜\n3) 웨어러블 사업부 성장 가속 — 애플 전체 매출의 ~10%\n\n■ 결론\n\nAirPods 카메라 탑재는 단순 업그레이드가 아닌 일상 AI 비서 플랫폼 진출. AAPL 장기 보유 논리를 강화합니다.",
    category:      "종목분석",
    categoryColor: "blue",
    subject:       "🍎 애플 (웨어러블·AI)",
    date:          "2026-05-13",
    updatedAt:     "2026.05.13 22:00",
    images:        ["/charts/apple-airpods.svg"],
  },
  {
    id:            "seed-009",
    title:         "CLARITY Act — 암호화폐 법제화, 트럼프의 코인 시장 신호",
    summary:       "트럼프가 CLARITY Act 투표 동일주에 비트코인·암호화폐 매수 발언을 했습니다. 과거 동일 패턴에서 시장이 반응했던 전례를 고려하면 법안 통과 시 제도 자금 유입이 본격화할 가능성이 높습니다.",
    body:          "■ CLARITY Act란\n\n디지털 자산을 증권 또는 상품으로 분류하는 기준을 명확히 하는 법안.\n\n■ 트럼프 발언\n\n\"지금 주식과 암호화폐를 매수하기 시작할 때다.\" — CLARITY Act 투표 당일\n\"Don't underestimate the man's words.\"\n\n■ 법안 통과 시 시장 영향\n\n1) 비트코인: 기관 투자 불확실성 해소 → ETF 추가 자금 유입\n2) 이더리움: \"증권 아님\" 명확화 → DeFi 재활성화\n3) 코인베이스(COIN): 규제 명확화 최대 수혜\n\n■ 결론\n\n트럼프 발언 + CLARITY Act 타이밍은 우연이 아닙니다. 법안 통과 여부를 집중 모니터링하세요.",
    category:      "매크로",
    categoryColor: "orange",
    subject:       "₿ 암호화폐 (CLARITY Act)",
    date:          "2026-05-13",
    updatedAt:     "2026.05.13 22:00",
    images:        ["/charts/crypto-clarity.svg"],
  },
  {
    id:            "seed-010",
    title:         "Google × SpaceX — 궤도 위성 데이터센터, AI 인프라 패러다임 전환",
    summary:       "구글과 스페이스X가 우주 궤도에 데이터센터를 공동 개발합니다. AI 수요 급증으로 지상 데이터센터 전력·냉각이 한계에 달한 가운데 위성 기반 인프라가 구조적 해결책으로 부상했습니다.",
    body:          "■ 핵심 소식\n\n\"Google and SpaceX are in talks to launch data centers into orbit amid surging AI demand.\" — WSJ\n\n■ 왜 우주 데이터센터인가\n\n• 전력: AI 클러스터 1개 = 소도시 연간 전력 소비\n• 냉각: 발열 처리 비용이 운영비 40%+\n• 우주: 무한 태양광 + 자연 방열 → 두 제약 모두 해소\n\n■ 구글·SpaceX 각자의 이해관계\n\n구글: GCP 용량 확장 + 스타링크 연결성\nSpaceX: 새 B2B 사업 + 스타십 발사 수요 창출\n\n■ 투자 접근법\n\n• GOOGL: 직접 수혜\n• RKLB: 소형 위성 발사 수요 증가\n\n■ 결론\n\n우주 데이터센터 투자 시계는 지금부터입니다.",
    category:      "섹터",
    categoryColor: "mint",
    subject:       "🛸 Google·SpaceX (우주·AI인프라)",
    date:          "2026-05-13",
    updatedAt:     "2026.05.13 22:00",
    images:        ["/charts/spacex-orbital.svg"],
  },
];
