// Comprehensive stock search registry — symbol + English name + Korean name
export const STOCK_SEARCH_DB: { symbol: string; name: string; nameKo?: string }[] = [
  // ── Mega-cap / S&P 500 Core ────────────────────────────────────────────────
  { symbol: "AAPL",  name: "Apple Inc.",                         nameKo: "애플" },
  { symbol: "MSFT",  name: "Microsoft Corp.",                    nameKo: "마이크로소프트" },
  { symbol: "NVDA",  name: "NVIDIA Corp.",                       nameKo: "엔비디아" },
  { symbol: "AMZN",  name: "Amazon.com Inc.",                    nameKo: "아마존" },
  { symbol: "GOOGL", name: "Alphabet Inc. (Class A)",            nameKo: "구글 알파벳" },
  { symbol: "GOOG",  name: "Alphabet Inc. (Class C)",            nameKo: "구글 알파벳" },
  { symbol: "META",  name: "Meta Platforms Inc.",                nameKo: "메타" },
  { symbol: "TSLA",  name: "Tesla Inc.",                         nameKo: "테슬라" },
  { symbol: "AVGO",  name: "Broadcom Inc.",                      nameKo: "브로드컴" },
  { symbol: "ORCL",  name: "Oracle Corp.",                       nameKo: "오라클" },
  { symbol: "BRK-B", name: "Berkshire Hathaway Inc. (B)",        nameKo: "버크셔 해서웨이" },
  { symbol: "BRK-A", name: "Berkshire Hathaway Inc. (A)",        nameKo: "버크셔 해서웨이" },
  { symbol: "LLY",   name: "Eli Lilly and Co.",                  nameKo: "일라이릴리" },
  { symbol: "JPM",   name: "JPMorgan Chase & Co.",               nameKo: "JP모건" },
  { symbol: "V",     name: "Visa Inc.",                          nameKo: "비자" },
  { symbol: "MA",    name: "Mastercard Inc.",                    nameKo: "마스터카드" },
  { symbol: "UNH",   name: "UnitedHealth Group Inc.",            nameKo: "유나이티드헬스" },
  { symbol: "XOM",   name: "Exxon Mobil Corp.",                  nameKo: "엑슨모빌" },
  { symbol: "COST",  name: "Costco Wholesale Corp.",             nameKo: "코스트코" },
  { symbol: "HD",    name: "Home Depot Inc.",                    nameKo: "홈디포" },
  { symbol: "PG",    name: "Procter & Gamble Co.",               nameKo: "P&G 프록터앤갬블" },
  { symbol: "NFLX",  name: "Netflix Inc.",                       nameKo: "넷플릭스" },
  { symbol: "CRM",   name: "Salesforce Inc.",                    nameKo: "세일즈포스" },
  { symbol: "BAC",   name: "Bank of America Corp.",              nameKo: "뱅크오브아메리카" },
  { symbol: "WMT",   name: "Walmart Inc.",                       nameKo: "월마트" },
  { symbol: "MRK",   name: "Merck & Co. Inc.",                   nameKo: "머크" },
  { symbol: "KO",    name: "Coca-Cola Co.",                      nameKo: "코카콜라" },
  { symbol: "CVX",   name: "Chevron Corp.",                      nameKo: "쉐브론" },
  { symbol: "ABBV",  name: "AbbVie Inc.",                        nameKo: "애브비" },
  { symbol: "TMO",   name: "Thermo Fisher Scientific Inc.",      nameKo: "써모피셔" },
  { symbol: "CSCO",  name: "Cisco Systems Inc.",                 nameKo: "시스코" },
  { symbol: "ABT",   name: "Abbott Laboratories",               nameKo: "애보트" },
  { symbol: "ACN",   name: "Accenture plc",                      nameKo: "액센추어" },
  { symbol: "GS",    name: "Goldman Sachs Group Inc.",           nameKo: "골드만삭스" },
  { symbol: "PEP",   name: "PepsiCo Inc.",                       nameKo: "펩시코" },
  { symbol: "WFC",   name: "Wells Fargo & Co.",                  nameKo: "웰스파고" },
  { symbol: "AXP",   name: "American Express Co.",               nameKo: "아메리칸익스프레스" },
  { symbol: "MCD",   name: "McDonald's Corp.",                   nameKo: "맥도날드" },
  { symbol: "NKE",   name: "Nike Inc.",                          nameKo: "나이키" },
  { symbol: "TXN",   name: "Texas Instruments Inc.",             nameKo: "텍사스인스트루먼트" },
  { symbol: "PM",    name: "Philip Morris International",        nameKo: "필립모리스" },
  { symbol: "CAT",   name: "Caterpillar Inc.",                   nameKo: "캐터필러" },
  { symbol: "RTX",   name: "RTX Corp. (Raytheon)",               nameKo: "레이시온 RTX" },
  { symbol: "GE",    name: "GE Aerospace",                       nameKo: "GE 에어로스페이스" },
  { symbol: "HON",   name: "Honeywell International Inc.",       nameKo: "허니웰" },
  { symbol: "AMGN",  name: "Amgen Inc.",                         nameKo: "암젠" },
  { symbol: "DHR",   name: "Danaher Corp.",                      nameKo: "다나허" },
  { symbol: "IBM",   name: "IBM Corp.",                          nameKo: "IBM" },
  { symbol: "MDT",   name: "Medtronic plc",                      nameKo: "메드트로닉" },
  { symbol: "ETN",   name: "Eaton Corp.",                        nameKo: "이튼" },
  { symbol: "SLB",   name: "SLB (Schlumberger)",                 nameKo: "슐럼버거" },
  { symbol: "BLK",   name: "BlackRock Inc.",                     nameKo: "블랙록" },
  { symbol: "ISRG",  name: "Intuitive Surgical Inc.",            nameKo: "인튜이티브서지컬" },
  { symbol: "ADP",   name: "Automatic Data Processing Inc.",     nameKo: "ADP" },
  { symbol: "SBUX",  name: "Starbucks Corp.",                    nameKo: "스타벅스" },
  { symbol: "CME",   name: "CME Group Inc.",                     nameKo: "CME 그룹" },
  { symbol: "DIS",   name: "Walt Disney Co.",                    nameKo: "디즈니" },
  { symbol: "PYPL",  name: "PayPal Holdings Inc.",               nameKo: "페이팔" },
  { symbol: "GILD",  name: "Gilead Sciences Inc.",               nameKo: "길리어드" },
  { symbol: "REGN",  name: "Regeneron Pharmaceuticals Inc.",     nameKo: "리제너론" },
  { symbol: "VRTX",  name: "Vertex Pharmaceuticals Inc.",        nameKo: "버텍스" },
  { symbol: "PLD",   name: "Prologis Inc.",                      nameKo: "프롤로지스" },
  { symbol: "AMT",   name: "American Tower Corp.",               nameKo: "아메리칸타워" },
  { symbol: "EQIX",  name: "Equinix Inc.",                       nameKo: "이퀴닉스" },
  { symbol: "CCI",   name: "Crown Castle Inc.",                  nameKo: "크라운캐슬" },
  { symbol: "SHW",   name: "Sherwin-Williams Co.",               nameKo: "셔윈윌리엄스" },
  { symbol: "LIN",   name: "Linde plc",                          nameKo: "린데" },
  { symbol: "CI",    name: "Cigna Group",                        nameKo: "시그나" },
  { symbol: "SPGI",  name: "S&P Global Inc.",                    nameKo: "S&P 글로벌" },
  { symbol: "MCO",   name: "Moody's Corp.",                      nameKo: "무디스" },
  { symbol: "BX",    name: "Blackstone Inc.",                    nameKo: "블랙스톤" },
  { symbol: "KKR",   name: "KKR & Co. Inc.",                     nameKo: "KKR" },
  { symbol: "APO",   name: "Apollo Global Management Inc.",      nameKo: "아폴로" },
  { symbol: "MS",    name: "Morgan Stanley",                     nameKo: "모건스탠리" },
  { symbol: "C",     name: "Citigroup Inc.",                     nameKo: "씨티그룹" },
  { symbol: "USB",   name: "U.S. Bancorp" },
  { symbol: "PNC",   name: "PNC Financial Services Group" },
  { symbol: "TFC",   name: "Truist Financial Corp." },
  { symbol: "COF",   name: "Capital One Financial Corp.",        nameKo: "캐피탈원" },
  { symbol: "SCHW",  name: "Charles Schwab Corp.",               nameKo: "찰스슈왑" },
  { symbol: "IBKR",  name: "Interactive Brokers Group Inc.",     nameKo: "인터랙티브브로커스" },
  { symbol: "T",     name: "AT&T Inc.",                          nameKo: "AT&T" },
  { symbol: "VZ",    name: "Verizon Communications Inc.",        nameKo: "버라이즌" },
  { symbol: "TMUS",  name: "T-Mobile US Inc.",                   nameKo: "티모바일" },
  { symbol: "F",     name: "Ford Motor Co.",                     nameKo: "포드" },
  { symbol: "GM",    name: "General Motors Co.",                 nameKo: "GM 제너럴모터스" },
  // ── NASDAQ 100 / Tech ─────────────────────────────────────────────────────
  { symbol: "AMD",   name: "Advanced Micro Devices Inc.",        nameKo: "AMD" },
  { symbol: "ADBE",  name: "Adobe Inc.",                         nameKo: "어도비" },
  { symbol: "QCOM",  name: "Qualcomm Inc.",                      nameKo: "퀄컴" },
  { symbol: "INTC",  name: "Intel Corp.",                        nameKo: "인텔" },
  { symbol: "AMAT",  name: "Applied Materials Inc.",             nameKo: "어플라이드 머티리얼즈" },
  { symbol: "LRCX",  name: "Lam Research Corp.",                 nameKo: "램리서치" },
  { symbol: "KLAC",  name: "KLA Corp.",                          nameKo: "KLA" },
  { symbol: "MRVL",  name: "Marvell Technology Inc.",            nameKo: "마벨" },
  { symbol: "SNPS",  name: "Synopsys Inc.",                      nameKo: "시놉시스" },
  { symbol: "CDNS",  name: "Cadence Design Systems Inc.",        nameKo: "케이던스" },
  { symbol: "MU",    name: "Micron Technology Inc.",             nameKo: "마이크론" },
  { symbol: "MCHP",  name: "Microchip Technology Inc.",          nameKo: "마이크로칩테크" },
  { symbol: "ON",    name: "ON Semiconductor Corp.",             nameKo: "온세미" },
  { symbol: "MPWR",  name: "Monolithic Power Systems Inc.",      nameKo: "모놀리식파워" },
  { symbol: "STX",   name: "Seagate Technology Holdings",        nameKo: "씨게이트" },
  { symbol: "WDC",   name: "Western Digital Corp.",              nameKo: "웨스턴디지털" },
  { symbol: "HPQ",   name: "HP Inc.",                            nameKo: "HP" },
  { symbol: "HPE",   name: "Hewlett Packard Enterprise Co.",     nameKo: "HPE" },
  { symbol: "DELL",  name: "Dell Technologies Inc.",             nameKo: "델" },
  { symbol: "PANW",  name: "Palo Alto Networks Inc.",            nameKo: "팔로알토 네트웍스" },
  { symbol: "FTNT",  name: "Fortinet Inc.",                      nameKo: "포티넷" },
  { symbol: "CRWD",  name: "CrowdStrike Holdings Inc.",          nameKo: "크라우드스트라이크" },
  { symbol: "ZS",    name: "Zscaler Inc.",                       nameKo: "지스케일러" },
  { symbol: "CYBR",  name: "CyberArk Software Ltd.",             nameKo: "사이버아크" },
  { symbol: "S",     name: "SentinelOne Inc.",                   nameKo: "센티넬원" },
  { symbol: "TEAM",  name: "Atlassian Corp.",                    nameKo: "아틀라시안" },
  { symbol: "DDOG",  name: "Datadog Inc.",                       nameKo: "데이터독" },
  { symbol: "SNOW",  name: "Snowflake Inc.",                     nameKo: "스노우플레이크" },
  { symbol: "NET",   name: "Cloudflare Inc.",                    nameKo: "클라우드플레어" },
  { symbol: "MDB",   name: "MongoDB Inc.",                       nameKo: "몽고DB" },
  { symbol: "OKTA",  name: "Okta Inc.",                          nameKo: "옥타" },
  { symbol: "WDAY",  name: "Workday Inc.",                       nameKo: "워크데이" },
  { symbol: "NOW",   name: "ServiceNow Inc.",                    nameKo: "서비스나우" },
  { symbol: "ZM",    name: "Zoom Video Communications Inc.",     nameKo: "줌" },
  { symbol: "SHOP",  name: "Shopify Inc.",                       nameKo: "쇼피파이" },
  { symbol: "HUBS",  name: "HubSpot Inc.",                       nameKo: "허브스팟" },
  { symbol: "TTD",   name: "Trade Desk Inc.",                    nameKo: "트레이드데스크" },
  { symbol: "GTLB",  name: "GitLab Inc.",                        nameKo: "깃랩" },
  { symbol: "LYFT",  name: "Lyft Inc.",                          nameKo: "리프트" },
  { symbol: "UBER",  name: "Uber Technologies Inc.",             nameKo: "우버" },
  { symbol: "ABNB",  name: "Airbnb Inc.",                        nameKo: "에어비앤비" },
  { symbol: "DASH",  name: "DoorDash Inc.",                      nameKo: "도어대시" },
  { symbol: "PINS",  name: "Pinterest Inc.",                     nameKo: "핀터레스트" },
  { symbol: "SNAP",  name: "Snap Inc.",                          nameKo: "스냅" },
  { symbol: "RDDT",  name: "Reddit Inc.",                        nameKo: "레딧" },
  { symbol: "HOOD",  name: "Robinhood Markets Inc.",             nameKo: "로빈후드" },
  { symbol: "PLTR",  name: "Palantir Technologies Inc.",         nameKo: "팔란티어" },
  { symbol: "AI",    name: "C3.ai Inc.",                         nameKo: "C3 AI" },
  { symbol: "PATH",  name: "UiPath Inc.",                        nameKo: "유아이패스" },
  { symbol: "SOUN",  name: "SoundHound AI Inc.",                 nameKo: "사운드하운드" },
  { symbol: "INTU",  name: "Intuit Inc.",                        nameKo: "인튜이트" },
  // ── Popular / Trending ────────────────────────────────────────────────────
  { symbol: "COIN",  name: "Coinbase Global Inc.",               nameKo: "코인베이스" },
  { symbol: "CRCL",  name: "Circle Internet Group Inc.",         nameKo: "써클" },
  { symbol: "MSTR",  name: "MicroStrategy Inc.",                 nameKo: "마이크로스트래티지" },
  { symbol: "MARA",  name: "MARA Holdings Inc.",                 nameKo: "마라홀딩스" },
  { symbol: "RIOT",  name: "Riot Platforms Inc.",                nameKo: "라이엇플랫폼" },
  { symbol: "HUT",   name: "Hut 8 Corp.",                        nameKo: "헛8" },
  { symbol: "ARM",   name: "Arm Holdings plc",                   nameKo: "ARM 홀딩스" },
  { symbol: "SMCI",  name: "Super Micro Computer Inc.",          nameKo: "슈퍼마이크로" },
  { symbol: "ASML",  name: "ASML Holding N.V.",                  nameKo: "ASML" },
  { symbol: "TSM",   name: "Taiwan Semiconductor Mfg. (ADR)",   nameKo: "TSMC 대만반도체" },
  { symbol: "RKLB",  name: "Rocket Lab USA Inc.",                nameKo: "로켓랩" },
  { symbol: "LUNR",  name: "Intuitive Machines Inc.",            nameKo: "인튜이티브머신즈" },
  { symbol: "ASTS",  name: "AST SpaceMobile Inc.",               nameKo: "AST 스페이스모바일" },
  { symbol: "RDW",   name: "Redwire Corp.",                      nameKo: "레드와이어" },
  { symbol: "IONQ",  name: "IonQ Inc.",                          nameKo: "아이온큐" },
  { symbol: "QBTS",  name: "D-Wave Quantum Inc.",                nameKo: "D-웨이브" },
  { symbol: "RGTI",  name: "Rigetti Computing Inc.",             nameKo: "리게티컴퓨팅" },
  { symbol: "QUBT",  name: "Quantum Computing Inc.",             nameKo: "퀀텀컴퓨팅" },
  { symbol: "JOBY",  name: "Joby Aviation Inc.",                 nameKo: "조비에비에이션" },
  { symbol: "ACHR",  name: "Archer Aviation Inc.",               nameKo: "아처에비에이션" },
  { symbol: "BBAI",  name: "BigBear.ai Holdings Inc.",           nameKo: "빅베어AI" },
  { symbol: "KULR",  name: "KULR Technology Group Inc." },
  // ── Biotech / Healthcare ──────────────────────────────────────────────────
  { symbol: "MRNA",  name: "Moderna Inc.",                       nameKo: "모더나" },
  { symbol: "BNTX",  name: "BioNTech SE",                        nameKo: "바이오엔텍" },
  { symbol: "PFE",   name: "Pfizer Inc.",                        nameKo: "화이자" },
  { symbol: "BMY",   name: "Bristol-Myers Squibb Co.",           nameKo: "브리스톨마이어스" },
  { symbol: "BIIB",  name: "Biogen Inc.",                        nameKo: "바이오젠" },
  { symbol: "ILMN",  name: "Illumina Inc.",                      nameKo: "일루미나" },
  { symbol: "GEHC",  name: "GE HealthCare Technologies Inc.",    nameKo: "GE헬스케어" },
  { symbol: "HCA",   name: "HCA Healthcare Inc.",                nameKo: "HCA헬스케어" },
  { symbol: "CVS",   name: "CVS Health Corp.",                   nameKo: "CVS헬스" },
  { symbol: "SYK",   name: "Stryker Corp.",                      nameKo: "스트라이커" },
  { symbol: "BSX",   name: "Boston Scientific Corp.",            nameKo: "보스턴사이언티픽" },
  { symbol: "DXCM",  name: "DexCom Inc.",                        nameKo: "덱스콤" },
  { symbol: "ALGN",  name: "Align Technology Inc.",              nameKo: "얼라인테크놀로지" },
  { symbol: "RMD",   name: "ResMed Inc.",                        nameKo: "레스메드" },
  { symbol: "BDX",   name: "Becton Dickinson and Co.",           nameKo: "벡톤디킨슨" },
  { symbol: "ALNY",  name: "Alnylam Pharmaceuticals Inc.",       nameKo: "알닐람" },
  // ── EV / Clean Energy ─────────────────────────────────────────────────────
  { symbol: "RIVN",  name: "Rivian Automotive Inc.",             nameKo: "리비안" },
  { symbol: "LCID",  name: "Lucid Group Inc.",                   nameKo: "루시드" },
  { symbol: "NIO",   name: "NIO Inc. (ADR)",                     nameKo: "니오" },
  { symbol: "XPEV",  name: "XPeng Inc. (ADR)",                   nameKo: "샤오펑 엑스펑" },
  { symbol: "LI",    name: "Li Auto Inc. (ADR)",                 nameKo: "리오토" },
  { symbol: "CHPT",  name: "ChargePoint Holdings Inc.",          nameKo: "차지포인트" },
  { symbol: "QS",    name: "QuantumScape Corp.",                 nameKo: "퀀텀스케이프" },
  { symbol: "PLUG",  name: "Plug Power Inc.",                    nameKo: "플러그파워" },
  { symbol: "FSLR",  name: "First Solar Inc.",                   nameKo: "퍼스트솔라" },
  { symbol: "ENPH",  name: "Enphase Energy Inc.",                nameKo: "엔페이즈" },
  { symbol: "SEDG",  name: "SolarEdge Technologies Inc.",        nameKo: "솔라엣지" },
  { symbol: "ALB",   name: "Albemarle Corp.",                    nameKo: "알버말" },
  { symbol: "MP",    name: "MP Materials Corp.",                 nameKo: "MP머티리얼즈" },
  // ── Energy ───────────────────────────────────────────────────────────────
  { symbol: "COP",   name: "ConocoPhillips",                     nameKo: "코노코필립스" },
  { symbol: "EOG",   name: "EOG Resources Inc." },
  { symbol: "BKR",   name: "Baker Hughes Co.",                   nameKo: "베이커휴즈" },
  { symbol: "OXY",   name: "Occidental Petroleum Corp.",         nameKo: "옥시덴탈" },
  { symbol: "HAL",   name: "Halliburton Co.",                    nameKo: "핼리버턴" },
  { symbol: "DVN",   name: "Devon Energy Corp." },
  { symbol: "PSX",   name: "Phillips 66",                        nameKo: "필립스66" },
  { symbol: "MPC",   name: "Marathon Petroleum Corp." },
  { symbol: "VLO",   name: "Valero Energy Corp.",                nameKo: "발레로" },
  // ── Industrial / Defense ──────────────────────────────────────────────────
  { symbol: "DE",    name: "Deere & Co.",                        nameKo: "존디어" },
  { symbol: "MMM",   name: "3M Co.",                             nameKo: "3M" },
  { symbol: "BA",    name: "Boeing Co.",                         nameKo: "보잉" },
  { symbol: "LMT",   name: "Lockheed Martin Corp.",              nameKo: "록히드마틴" },
  { symbol: "NOC",   name: "Northrop Grumman Corp.",             nameKo: "노스롭그루먼" },
  { symbol: "GD",    name: "General Dynamics Corp.",             nameKo: "제너럴다이내믹스" },
  { symbol: "LHX",   name: "L3Harris Technologies Inc.",         nameKo: "L3해리스" },
  { symbol: "LDOS",  name: "Leidos Holdings Inc.",               nameKo: "레이도스" },
  { symbol: "AXON",  name: "Axon Enterprise Inc.",               nameKo: "액슨" },
  { symbol: "HII",   name: "Huntington Ingalls Industries Inc.", nameKo: "헌팅턴잉갈스" },
  { symbol: "TDG",   name: "TransDigm Group Inc.",               nameKo: "트랜스다임" },
  { symbol: "EMR",   name: "Emerson Electric Co.",               nameKo: "에머슨일렉트릭" },
  // ── Consumer / Retail ─────────────────────────────────────────────────────
  { symbol: "TGT",   name: "Target Corp.",                       nameKo: "타겟" },
  { symbol: "LOW",   name: "Lowe's Companies Inc.",              nameKo: "로우스" },
  { symbol: "DG",    name: "Dollar General Corp.",               nameKo: "달러제너럴" },
  { symbol: "YUM",   name: "Yum! Brands Inc.",                   nameKo: "얌브랜즈" },
  { symbol: "CMG",   name: "Chipotle Mexican Grill Inc.",        nameKo: "치폴레" },
  { symbol: "QSR",   name: "Restaurant Brands International Inc.", nameKo: "버거킹 팀홀튼" },
  { symbol: "DPZ",   name: "Domino's Pizza Inc.",                nameKo: "도미노피자" },
  { symbol: "SHAK",  name: "Shake Shack Inc.",                   nameKo: "쉐이크쉑" },
  { symbol: "WING",  name: "Wingstop Inc.",                      nameKo: "윙스탑" },
  { symbol: "TXRH",  name: "Texas Roadhouse Inc.",               nameKo: "텍사스로드하우스" },
  { symbol: "LULU",  name: "Lululemon Athletica Inc.",           nameKo: "룰루레몬" },
  { symbol: "ONON",  name: "On Holding AG",                      nameKo: "온러닝" },
  { symbol: "UAA",   name: "Under Armour Inc. (Class A)",        nameKo: "언더아머" },
  { symbol: "CROX",  name: "Crocs Inc.",                         nameKo: "크록스" },
  { symbol: "SKX",   name: "Skechers USA Inc.",                  nameKo: "스케쳐스" },
  { symbol: "RL",    name: "Ralph Lauren Corp.",                  nameKo: "폴로 랄프로렌" },
  { symbol: "PVH",   name: "PVH Corp. (Calvin Klein, Tommy Hilfiger)", nameKo: "캘빈클라인 타미힐피거" },
  { symbol: "TPR",   name: "Tapestry Inc. (Coach, Kate Spade)",  nameKo: "코치 케이트스페이드" },
  { symbol: "CPRI",  name: "Capri Holdings Ltd. (Michael Kors, Versace)", nameKo: "마이클코어스 베르사체" },
  { symbol: "HBI",   name: "Hanesbrands Inc.",                   nameKo: "헤인즈" },
  { symbol: "ETSY",  name: "Etsy Inc.",                          nameKo: "엣시" },
  { symbol: "EBAY",  name: "eBay Inc.",                          nameKo: "이베이" },
  { symbol: "CHWY",  name: "Chewy Inc.",                         nameKo: "츄이" },
  { symbol: "W",     name: "Wayfair Inc.",                       nameKo: "웨이페어" },
  // ── Media / Entertainment ─────────────────────────────────────────────────
  { symbol: "SPOT",  name: "Spotify Technology S.A.",            nameKo: "스포티파이" },
  { symbol: "WBD",   name: "Warner Bros. Discovery Inc.",        nameKo: "워너브라더스" },
  { symbol: "PARA",  name: "Paramount Global",                   nameKo: "파라마운트" },
  { symbol: "LYV",   name: "Live Nation Entertainment Inc.",     nameKo: "라이브네이션" },
  { symbol: "RBLX",  name: "Roblox Corp.",                       nameKo: "로블록스" },
  { symbol: "TTWO",  name: "Take-Two Interactive Software Inc.", nameKo: "테이크투" },
  { symbol: "EA",    name: "Electronic Arts Inc.",               nameKo: "일렉트로닉아츠" },
  // ── Real Estate / REITs ───────────────────────────────────────────────────
  { symbol: "SPG",   name: "Simon Property Group Inc.",          nameKo: "사이먼프라퍼티" },
  { symbol: "O",     name: "Realty Income Corp.",                nameKo: "리얼티인컴" },
  { symbol: "DLR",   name: "Digital Realty Trust Inc.",          nameKo: "디지털리얼티" },
  { symbol: "WELL",  name: "Welltower Inc.",                      nameKo: "웰타워" },
  { symbol: "PSA",   name: "Public Storage",                     nameKo: "퍼블릭스토리지" },
  // ── Materials ────────────────────────────────────────────────────────────
  { symbol: "FCX",   name: "Freeport-McMoRan Inc.",              nameKo: "프리포트맥모란" },
  { symbol: "NEM",   name: "Newmont Corp.",                      nameKo: "뉴몬트" },
  { symbol: "AA",    name: "Alcoa Corp.",                        nameKo: "알코아" },
  { symbol: "DOW",   name: "Dow Inc.",                           nameKo: "다우" },
  { symbol: "DD",    name: "DuPont de Nemours Inc.",             nameKo: "듀폰" },
  // ── Transport / Logistics ─────────────────────────────────────────────────
  { symbol: "UPS",   name: "United Parcel Service Inc.",         nameKo: "UPS" },
  { symbol: "FDX",   name: "FedEx Corp.",                        nameKo: "페덱스" },
  { symbol: "DAL",   name: "Delta Air Lines Inc.",               nameKo: "델타항공" },
  { symbol: "UAL",   name: "United Airlines Holdings Inc.",      nameKo: "유나이티드항공" },
  { symbol: "AAL",   name: "American Airlines Group Inc.",       nameKo: "아메리칸항공" },
  { symbol: "LUV",   name: "Southwest Airlines Co.",             nameKo: "사우스웨스트항공" },
  { symbol: "JBHT",  name: "J.B. Hunt Transport Services Inc.",  nameKo: "JB헌트" },
  { symbol: "ODFL",  name: "Old Dominion Freight Line Inc.",     nameKo: "올드도미니언" },
  // ── ETFs ──────────────────────────────────────────────────────────────────
  { symbol: "SPY",   name: "SPDR S&P 500 ETF Trust",             nameKo: "S&P500 ETF" },
  { symbol: "QQQ",   name: "Invesco QQQ Trust (NASDAQ 100)",     nameKo: "나스닥100 ETF" },
  { symbol: "IWM",   name: "iShares Russell 2000 ETF",           nameKo: "러셀2000 ETF" },
  { symbol: "DIA",   name: "SPDR Dow Jones Industrial Average ETF", nameKo: "다우존스 ETF" },
  { symbol: "VOO",   name: "Vanguard S&P 500 ETF",               nameKo: "뱅가드 S&P500" },
  { symbol: "VTI",   name: "Vanguard Total Stock Market ETF",    nameKo: "뱅가드 전체시장" },
  { symbol: "VGT",   name: "Vanguard Information Technology ETF",nameKo: "뱅가드 IT ETF" },
  { symbol: "GLD",   name: "SPDR Gold Shares",                   nameKo: "금 ETF" },
  { symbol: "SLV",   name: "iShares Silver Trust",               nameKo: "은 ETF" },
  { symbol: "TLT",   name: "iShares 20+ Year Treasury Bond ETF", nameKo: "미국장기채 ETF" },
  { symbol: "XLK",   name: "Technology Select Sector SPDR Fund", nameKo: "기술섹터 ETF" },
  { symbol: "XLF",   name: "Financial Select Sector SPDR Fund",  nameKo: "금융섹터 ETF" },
  { symbol: "XLE",   name: "Energy Select Sector SPDR Fund",     nameKo: "에너지섹터 ETF" },
  { symbol: "XLV",   name: "Health Care Select Sector SPDR Fund",nameKo: "헬스케어섹터 ETF" },
  { symbol: "ARKK",  name: "ARK Innovation ETF",                 nameKo: "ARK 이노베이션 ETF" },
  { symbol: "ARKX",  name: "ARK Space Exploration & Innovation ETF", nameKo: "ARK 스페이스 ETF" },
  { symbol: "ARKG",  name: "ARK Genomic Revolution ETF",         nameKo: "ARK 유전체 ETF" },
  { symbol: "TQQQ",  name: "ProShares UltraPro QQQ (3x)",        nameKo: "나스닥 3배 레버리지" },
  { symbol: "SQQQ",  name: "ProShares UltraPro Short QQQ (-3x)", nameKo: "나스닥 3배 인버스" },
  { symbol: "SOXL",  name: "Direxion Daily Semiconductor Bull 3X",nameKo: "반도체 3배 레버리지" },
  { symbol: "SOXS",  name: "Direxion Daily Semiconductor Bear 3X",nameKo: "반도체 3배 인버스" },
  { symbol: "SPXL",  name: "Direxion Daily S&P 500 Bull 3X Shares",nameKo: "S&P500 3배 레버리지" },
  { symbol: "TSLL",  name: "Direxion Daily TSLA Bull 2X Shares", nameKo: "테슬라 2배 레버리지" },
  { symbol: "NVDL",  name: "GraniteShares 2x Long NVDA Daily ETF",nameKo: "엔비디아 2배 레버리지" },
  { symbol: "UFO",   name: "Procure Space ETF",                  nameKo: "우주 ETF" },
  { symbol: "BOTZ",  name: "Global X Robotics & AI ETF",         nameKo: "로봇 AI ETF" },
  // ── 13F Guru Holdings — 누락 종목 보완 ──────────────────────────────────────
  { symbol: "BKNG",  name: "Booking Holdings Inc.",               nameKo: "부킹닷컴 북킹홀딩스" },
  { symbol: "HLT",   name: "Hilton Worldwide Holdings Inc.",      nameKo: "힐튼" },
  { symbol: "RCL",   name: "Royal Caribbean Cruises Ltd.",        nameKo: "로열캐리비안 크루즈" },
  { symbol: "DKNG",  name: "DraftKings Inc.",                     nameKo: "드래프트킹스" },
  { symbol: "ROKU",  name: "Roku Inc.",                           nameKo: "로쿠" },
  { symbol: "SQ",    name: "Block Inc. (Square)",                 nameKo: "블록 스퀘어" },
  { symbol: "CPNG",  name: "Coupang Inc.",                        nameKo: "쿠팡" },
  { symbol: "KHC",   name: "Kraft Heinz Co.",                     nameKo: "크래프트하인즈" },
  { symbol: "STZ",   name: "Constellation Brands Inc.",           nameKo: "코로나맥주 컨스텔레이션" },
  { symbol: "DVA",   name: "DaVita Inc.",                         nameKo: "다비타" },
  { symbol: "CRSP",  name: "CRISPR Therapeutics AG",              nameKo: "크리스퍼" },
  { symbol: "NTLA",  name: "Intellia Therapeutics Inc.",          nameKo: "인텔리아테라퓨틱스" },
  { symbol: "RXRX",  name: "Recursion Pharmaceuticals Inc.",      nameKo: "리커전파마슈티컬" },
  { symbol: "NXPI",  name: "NXP Semiconductors N.V.",             nameKo: "NXP반도체" },
  { symbol: "COHR",  name: "Coherent Corp.",                      nameKo: "코히어런트" },
  { symbol: "SBAC",  name: "SBA Communications Corp.",            nameKo: "SBA커뮤니케이션즈" },
  { symbol: "BURL",  name: "Burlington Stores Inc.",              nameKo: "벌링턴" },
  { symbol: "MKL",   name: "Markel Group Inc.",                   nameKo: "마켈" },
  { symbol: "ACGL",  name: "Arch Capital Group Ltd.",             nameKo: "아치캐피탈" },
  { symbol: "CB",    name: "Chubb Ltd.",                          nameKo: "처브보험" },
  { symbol: "MTN",   name: "Vail Resorts Inc.",                   nameKo: "베일리조트" },
  { symbol: "PCOR",  name: "Procore Technologies Inc.",           nameKo: "프로코어" },
  { symbol: "SIRI",  name: "Sirius XM Holdings Inc.",             nameKo: "시리우스XM" },
  { symbol: "VRSN",  name: "Verisign Inc.",                       nameKo: "베리사인" },
  { symbol: "Z",     name: "Zillow Group Inc. (Class C)",         nameKo: "질로우" },
  { symbol: "ZG",    name: "Zillow Group Inc. (Class A)",         nameKo: "질로우" },
  { symbol: "CSGP",  name: "CoStar Group Inc.",                   nameKo: "코스타" },
  // ── 인기 / 트렌드 종목 ────────────────────────────────────────────────────
  { symbol: "APP",   name: "AppLovin Corp.",                      nameKo: "앱러빈" },
  { symbol: "AFRM",  name: "Affirm Holdings Inc.",                nameKo: "어펌" },
  { symbol: "SOFI",  name: "SoFi Technologies Inc.",              nameKo: "소파이" },
  { symbol: "UPST",  name: "Upstart Holdings Inc.",               nameKo: "업스타트" },
  { symbol: "LMND",  name: "Lemonade Inc.",                       nameKo: "레모네이드" },
  { symbol: "GME",   name: "GameStop Corp.",                      nameKo: "게임스탑" },
  { symbol: "AMC",   name: "AMC Entertainment Holdings Inc.",     nameKo: "AMC 영화관" },
  { symbol: "SPCE",  name: "Virgin Galactic Holdings Inc.",       nameKo: "버진갤럭틱" },
  { symbol: "OPEN",  name: "Opendoor Technologies Inc.",          nameKo: "오픈도어" },
  { symbol: "WKHS",  name: "Workhorse Group Inc.",                nameKo: "워크호스" },
  { symbol: "CLOV",  name: "Clover Health Investments Corp.",     nameKo: "클로버헬스" },
  { symbol: "MNDY",  name: "Monday.com Ltd.",                     nameKo: "먼데이닷컴" },
  { symbol: "FROG",  name: "JFrog Ltd.",                          nameKo: "J프로그" },
  { symbol: "CFLT",  name: "Confluent Inc.",                      nameKo: "컨플루언트" },
  { symbol: "DUOL",  name: "Duolingo Inc.",                       nameKo: "듀오링고" },
  { symbol: "BILL",  name: "BILL Holdings Inc.",                  nameKo: "빌닷컴" },
  { symbol: "ADSK",  name: "Autodesk Inc.",                       nameKo: "오토데스크" },
  { symbol: "SMAR",  name: "Smartsheet Inc.",                     nameKo: "스마트시트" },
  { symbol: "APPF",  name: "AppFolio Inc.",                       nameKo: "앱폴리오" },
  // ── 카지노 / 여행 / 레저 ────────────────────────────────────────────────────
  { symbol: "WYNN",  name: "Wynn Resorts Ltd.",                   nameKo: "윈리조트" },
  { symbol: "LVS",   name: "Las Vegas Sands Corp.",               nameKo: "라스베이거스샌즈" },
  { symbol: "MGM",   name: "MGM Resorts International",           nameKo: "MGM 리조트" },
  { symbol: "CZR",   name: "Caesars Entertainment Inc.",          nameKo: "시저스엔터테인먼트" },
  { symbol: "MAR",   name: "Marriott International Inc.",         nameKo: "메리어트" },
  { symbol: "H",     name: "Hyatt Hotels Corp.",                  nameKo: "하얏트" },
  { symbol: "IHG",   name: "InterContinental Hotels Group (ADR)", nameKo: "인터컨티넨탈 IHG" },
  { symbol: "CCL",   name: "Carnival Corp.",                      nameKo: "카니발크루즈" },
  { symbol: "NCLH",  name: "Norwegian Cruise Line Holdings Ltd.", nameKo: "노르웨이지안크루즈" },
  { symbol: "EXPE",  name: "Expedia Group Inc.",                  nameKo: "익스피디아" },
  { symbol: "TRIP",  name: "TripAdvisor Inc.",                    nameKo: "트립어드바이저" },
  // ── Global ADRs ───────────────────────────────────────────────────────────
  { symbol: "BABA",  name: "Alibaba Group Holding Ltd. (ADR)",   nameKo: "알리바바" },
  { symbol: "JD",    name: "JD.com Inc. (ADR)",                  nameKo: "징동 JD닷컴" },
  { symbol: "PDD",   name: "PDD Holdings Inc. (ADR)",            nameKo: "테무 PDD" },
  { symbol: "BIDU",  name: "Baidu Inc. (ADR)",                   nameKo: "바이두" },
  { symbol: "TCEHY", name: "Tencent Holdings Ltd. (OTC ADR)",    nameKo: "텐센트" },
  { symbol: "NTES",  name: "NetEase Inc. (ADR)",                 nameKo: "왕이 넷이즈" },
  { symbol: "BILI",  name: "Bilibili Inc. (ADR)",                nameKo: "비리비리" },
  { symbol: "SE",    name: "Sea Ltd. (ADR)",                     nameKo: "씨 가레나" },
  { symbol: "GRAB",  name: "Grab Holdings Ltd.",                 nameKo: "그랩" },
  { symbol: "MELI",  name: "MercadoLibre Inc.",                  nameKo: "메르카도리브레" },
  { symbol: "NU",    name: "Nu Holdings Ltd.",                   nameKo: "누뱅크" },
  { symbol: "SAP",   name: "SAP SE (ADR)",                       nameKo: "SAP" },
  { symbol: "TM",    name: "Toyota Motor Corp. (ADR)",           nameKo: "도요타" },
  { symbol: "SONY",  name: "Sony Group Corp. (ADR)",             nameKo: "소니" },
  { symbol: "NVO",   name: "Novo Nordisk A/S (ADR)",             nameKo: "노보노디스크" },
  { symbol: "AZN",   name: "AstraZeneca plc (ADR)",              nameKo: "아스트라제네카" },
  { symbol: "GSK",   name: "GSK plc (ADR)",                      nameKo: "GSK" },
  { symbol: "BP",    name: "BP plc (ADR)",                       nameKo: "BP" },
  { symbol: "SHEL",  name: "Shell plc (ADR)",                    nameKo: "쉘" },

  // ── 고배당 ETF (한국인 인기) ──────────────────────────────────────
  { symbol: "SCHD",  name: "Schwab US Dividend Equity ETF",       nameKo: "SCHD 배당ETF" },
  { symbol: "JEPI",  name: "JPMorgan Equity Premium Income ETF",  nameKo: "JEPI 배당ETF" },
  { symbol: "JEPQ",  name: "JPMorgan Nasdaq Equity Premium ETF",  nameKo: "JEPQ 배당ETF" },
  { symbol: "VYM",   name: "Vanguard High Dividend Yield ETF",    nameKo: "VYM 배당ETF" },
  { symbol: "DGRO",  name: "iShares Core Dividend Growth ETF",    nameKo: "DGRO 배당성장ETF" },
  { symbol: "SPYD",  name: "SPDR Portfolio S&P 500 High Div ETF", nameKo: "SPYD 고배당ETF" },
  { symbol: "DVY",   name: "iShares Select Dividend ETF",         nameKo: "DVY 배당ETF" },
  { symbol: "NOBL",  name: "ProShares S&P 500 Dividend Aristocrats ETF", nameKo: "NOBL 귀족주ETF" },
  { symbol: "DIVO",  name: "Amplify CWP Enhanced Dividend Income ETF", nameKo: "DIVO 배당ETF" },
  { symbol: "HDV",   name: "iShares Core High Dividend ETF",      nameKo: "HDV 고배당ETF" },
  { symbol: "FDVV",  name: "Fidelity High Dividend ETF",          nameKo: "FDVV 배당ETF" },
  { symbol: "PEY",   name: "Invesco High Yield Equity Dividend Achievers ETF", nameKo: "PEY 배당ETF" },

  // ── 커버드콜 ETF ─────────────────────────────────────────────────
  { symbol: "QYLD",  name: "Global X NASDAQ 100 Covered Call ETF", nameKo: "QYLD 커버드콜ETF" },
  { symbol: "XYLD",  name: "Global X S&P 500 Covered Call ETF",   nameKo: "XYLD 커버드콜ETF" },
  { symbol: "RYLD",  name: "Global X Russell 2000 Covered Call ETF", nameKo: "RYLD 커버드콜ETF" },
  { symbol: "TSLY",  name: "YieldMax TSLA Option Income Strategy ETF", nameKo: "TSLY 테슬라커버드콜" },
  { symbol: "NVDY",  name: "YieldMax NVDA Option Income Strategy ETF", nameKo: "NVDY 엔비디아커버드콜" },
  { symbol: "CONY",  name: "YieldMax COIN Option Income Strategy ETF", nameKo: "CONY 코인베이스커버드콜" },
  { symbol: "MSFO",  name: "YieldMax MSFT Option Income Strategy ETF", nameKo: "MSFO 마이크로소프트커버드콜" },
  { symbol: "AMZY",  name: "YieldMax AMZN Option Income Strategy ETF", nameKo: "AMZY 아마존커버드콜" },
  { symbol: "GOOGY", name: "YieldMax GOOGL Option Income Strategy ETF", nameKo: "GOOGY 구글커버드콜" },
  { symbol: "APLY",  name: "YieldMax AAPL Option Income Strategy ETF", nameKo: "APLY 애플커버드콜" },
  { symbol: "YMAX",  name: "YieldMax Universe Fund of Option Income ETFs", nameKo: "YMAX 커버드콜묶음" },

  // ── 레버리지/인버스 ETF ──────────────────────────────────────────
  { symbol: "UPRO",  name: "ProShares UltraPro S&P 500 (3x)",    nameKo: "UPRO S&P500 3배" },
  { symbol: "SPXS",  name: "Direxion Daily S&P 500 Bear 3x ETF", nameKo: "SPXS S&P500 3배인버스" },
  { symbol: "TECL",  name: "Direxion Daily Technology Bull 3x ETF", nameKo: "TECL 기술주3배" },
  { symbol: "LABU",  name: "Direxion Daily S&P Biotech Bull 3x ETF", nameKo: "LABU 바이오3배" },
  { symbol: "FNGU",  name: "MicroSectors FANG+ Index 3x Leveraged ETN", nameKo: "FNGU FANG3배" },
  { symbol: "TMF",   name: "Direxion Daily 20+ Year Treasury Bull 3x ETF", nameKo: "TMF 장기채3배" },
  { symbol: "TBT",   name: "ProShares UltraShort 20+ Year Treasury ETF", nameKo: "TBT 장기채2배인버스" },
  { symbol: "TNA",   name: "Direxion Daily Small Cap Bull 3x ETF", nameKo: "TNA 소형주3배" },
  { symbol: "FAS",   name: "Direxion Daily Financial Bull 3x ETF", nameKo: "FAS 금융3배" },
  { symbol: "CURE",  name: "Direxion Daily Healthcare Bull 3x ETF", nameKo: "CURE 헬스케어3배" },

  // ── 광범위 인덱스 ETF ────────────────────────────────────────────
  { symbol: "VXUS",  name: "Vanguard Total International Stock ETF", nameKo: "VXUS 해외주식ETF" },
  { symbol: "VT",    name: "Vanguard Total World Stock ETF",      nameKo: "VT 글로벌ETF" },
  { symbol: "IVV",   name: "iShares Core S&P 500 ETF",           nameKo: "IVV S&P500ETF" },
  { symbol: "QQQM",  name: "Invesco Nasdaq 100 ETF",              nameKo: "QQQM 나스닥100ETF" },
  { symbol: "VEA",   name: "Vanguard FTSE Developed Markets ETF", nameKo: "VEA 선진국ETF" },
  { symbol: "VWO",   name: "Vanguard FTSE Emerging Markets ETF",  nameKo: "VWO 신흥국ETF" },
  { symbol: "EEM",   name: "iShares MSCI Emerging Markets ETF",   nameKo: "EEM 신흥국ETF" },
  { symbol: "IWF",   name: "iShares Russell 1000 Growth ETF",     nameKo: "IWF 성장주ETF" },
  { symbol: "IWD",   name: "iShares Russell 1000 Value ETF",      nameKo: "IWD 가치주ETF" },
  { symbol: "VIG",   name: "Vanguard Dividend Appreciation ETF",  nameKo: "VIG 배당성장ETF" },

  // ── 섹터 ETF ─────────────────────────────────────────────────────
  { symbol: "XLI",   name: "Industrial Select Sector SPDR ETF",  nameKo: "XLI 산업섹터ETF" },
  { symbol: "XLC",   name: "Communication Services SPDR ETF",    nameKo: "XLC 통신섹터ETF" },
  { symbol: "XLY",   name: "Consumer Discretionary SPDR ETF",    nameKo: "XLY 소비재섹터ETF" },
  { symbol: "XLP",   name: "Consumer Staples SPDR ETF",          nameKo: "XLP 필수소비재ETF" },
  { symbol: "XLU",   name: "Utilities Select Sector SPDR ETF",   nameKo: "XLU 유틸리티ETF" },
  { symbol: "XLRE",  name: "Real Estate Select Sector SPDR ETF", nameKo: "XLRE 리츠섹터ETF" },
  { symbol: "XLB",   name: "Materials Select Sector SPDR ETF",   nameKo: "XLB 소재섹터ETF" },
  { symbol: "SMH",   name: "VanEck Semiconductor ETF",           nameKo: "SMH 반도체ETF" },
  { symbol: "SOXX",  name: "iShares Semiconductor ETF",          nameKo: "SOXX 반도체ETF" },
  { symbol: "IBB",   name: "iShares Biotechnology ETF",          nameKo: "IBB 바이오ETF" },
  { symbol: "ARKW",  name: "ARK Next Generation Internet ETF",   nameKo: "ARKW 인터넷ETF" },
  { symbol: "ARKF",  name: "ARK Fintech Innovation ETF",         nameKo: "ARKF 핀테크ETF" },
  { symbol: "ARKQ",  name: "ARK Autonomous Technology & Robotics ETF", nameKo: "ARKQ 자율주행로봇ETF" },

  // ── 채권 ETF ──────────────────────────────────────────────────────
  { symbol: "IEF",   name: "iShares 7-10 Year Treasury Bond ETF", nameKo: "IEF 중기채ETF" },
  { symbol: "SHY",   name: "iShares 1-3 Year Treasury Bond ETF", nameKo: "SHY 단기채ETF" },
  { symbol: "BND",   name: "Vanguard Total Bond Market ETF",     nameKo: "BND 채권ETF" },
  { symbol: "LQD",   name: "iShares iBoxx $ Investment Grade Corporate Bond ETF", nameKo: "LQD 회사채ETF" },
  { symbol: "HYG",   name: "iShares iBoxx $ High Yield Corporate Bond ETF", nameKo: "HYG 하이일드채권ETF" },
  { symbol: "AGG",   name: "iShares Core US Aggregate Bond ETF", nameKo: "AGG 종합채권ETF" },
  { symbol: "SGOV",  name: "iShares 0-3 Month Treasury Bond ETF", nameKo: "SGOV 초단기채ETF" },
  { symbol: "VGIT",  name: "Vanguard Intermediate-Term Treasury ETF", nameKo: "VGIT 중기국채ETF" },

  // ── 원자재/금 ETF ─────────────────────────────────────────────────
  { symbol: "IAU",   name: "iShares Gold Trust ETF",             nameKo: "IAU 금ETF" },
  { symbol: "GDX",   name: "VanEck Gold Miners ETF",             nameKo: "GDX 금광주ETF" },
  { symbol: "GDXJ",  name: "VanEck Junior Gold Miners ETF",      nameKo: "GDXJ 소형금광ETF" },
  { symbol: "USO",   name: "United States Oil Fund ETF",         nameKo: "USO 원유ETF" },
  { symbol: "PDBC",  name: "Invesco Optimum Yield Diversified Commodity ETF", nameKo: "PDBC 원자재ETF" },

  // ── 리츠 ETF & 개별 리츠 ─────────────────────────────────────────
  { symbol: "VNQ",   name: "Vanguard Real Estate ETF",           nameKo: "VNQ 리츠ETF" },
  { symbol: "VICI",  name: "VICI Properties Inc.",               nameKo: "비시 프로퍼티" },

  // ── 국가별 ETF ──────────────────────────────────────────────────
  { symbol: "INDA",  name: "iShares MSCI India ETF",             nameKo: "INDA 인도ETF" },
  { symbol: "EWT",   name: "iShares MSCI Taiwan ETF",            nameKo: "EWT 대만ETF" },
  { symbol: "EWJ",   name: "iShares MSCI Japan ETF",             nameKo: "EWJ 일본ETF" },
  { symbol: "FXI",   name: "iShares China Large-Cap ETF",        nameKo: "FXI 중국ETF" },
  { symbol: "KWEB",  name: "KraneShares CSI China Internet ETF", nameKo: "KWEB 중국인터넷ETF" },
  { symbol: "EWZ",   name: "iShares MSCI Brazil ETF",            nameKo: "EWZ 브라질ETF" },
  { symbol: "EWY",   name: "iShares MSCI South Korea ETF",       nameKo: "EWY 한국ETF" },

  // ── 인기 성장주 (나스닥/NYSE 상장) ─────────────────────────────
  { symbol: "ZETA",  name: "Zeta Global Holdings Corp.",         nameKo: "제타글로벌" },
  { symbol: "SERV",  name: "Serve Robotics Inc.",                nameKo: "서브로보틱스" },
  { symbol: "VRT",   name: "Vertiv Holdings Co.",                nameKo: "버티브홀딩스" },
  { symbol: "VEEV",  name: "Veeva Systems Inc.",                 nameKo: "비바시스템즈" },
  { symbol: "CELH",  name: "Celsius Holdings Inc.",              nameKo: "셀시우스" },
  { symbol: "EVGO",  name: "EVgo Inc.",                          nameKo: "이브고" },
  { symbol: "BLNK",  name: "Blink Charging Co.",                 nameKo: "블링크차징" },
  { symbol: "BE",    name: "Bloom Energy Corp.",                 nameKo: "블룸에너지" },
  { symbol: "RKT",   name: "Rocket Companies Inc.",              nameKo: "로켓컴퍼니즈" },
  { symbol: "LC",    name: "LendingClub Corp.",                  nameKo: "렌딩클럽" },
  { symbol: "GLBE",  name: "Global-E Online Ltd.",               nameKo: "글로벌이" },
  { symbol: "ESTC",  name: "Elastic N.V.",                       nameKo: "엘라스틱" },
  { symbol: "ZI",    name: "ZoomInfo Technologies Inc.",         nameKo: "줌인포" },
  { symbol: "TOST",  name: "Toast Inc.",                         nameKo: "토스트" },
  { symbol: "PCVX",  name: "Vaxcyte Inc.",                       nameKo: "백사이트" },
  { symbol: "SANA",  name: "Sana Biotechnology Inc.",            nameKo: "사나바이오" },
  { symbol: "CERE",  name: "Cerevel Therapeutics Holdings Inc.", nameKo: "서레벨테라퓨틱스" },
  { symbol: "BEAM",  name: "Beam Therapeutics Inc.",             nameKo: "빔테라퓨틱스" },
  { symbol: "EDIT",  name: "Editas Medicine Inc.",               nameKo: "에디타스메디신" },

  // ── 방산/항공우주 ─────────────────────────────────────────────────
  { symbol: "KTOS",  name: "Kratos Defense & Security Solutions Inc.", nameKo: "크라토스방산" },
  { symbol: "SAIC",  name: "Science Applications International Corp.", nameKo: "SAIC" },
  { symbol: "HEICO", name: "HEICO Corp.",                        nameKo: "헤이코" },
  { symbol: "HEI",   name: "HEICO Corp. Class A",                nameKo: "헤이코A" },

  // ── 유틸리티/에너지 ──────────────────────────────────────────────
  { symbol: "NEE",   name: "NextEra Energy Inc.",                nameKo: "넥스트에라에너지" },
  { symbol: "DUK",   name: "Duke Energy Corp.",                  nameKo: "듀크에너지" },
  { symbol: "SO",    name: "Southern Company",                   nameKo: "서던컴퍼니" },
  { symbol: "D",     name: "Dominion Energy Inc.",               nameKo: "도미니언에너지" },
  { symbol: "AEP",   name: "American Electric Power Co.",        nameKo: "아메리칸일렉트릭파워" },
  { symbol: "EXC",   name: "Exelon Corp.",                       nameKo: "엑셀론" },
  { symbol: "CEG",   name: "Constellation Energy Corp.",         nameKo: "컨스텔레이션에너지" },
  { symbol: "PCG",   name: "PG&E Corp.",                         nameKo: "PG&E" },
  { symbol: "VST",   name: "Vistra Corp.",                       nameKo: "비스트라" },
  { symbol: "NRG",   name: "NRG Energy Inc.",                    nameKo: "NRG에너지" },

  // ── 통신 ───────────────────────────────────────────────────────
  { symbol: "LBRDK", name: "Liberty Broadband Corp.",            nameKo: "리버티브로드밴드" },
  { symbol: "CHTR",  name: "Charter Communications Inc.",        nameKo: "차터커뮤니케이션즈" },
  { symbol: "CMCSA", name: "Comcast Corp.",                      nameKo: "컴캐스트" },

  // ── 금융/보험 ────────────────────────────────────────────────────
  { symbol: "DFS",   name: "Discover Financial Services",        nameKo: "디스커버파이낸셜" },
  { symbol: "PRU",   name: "Prudential Financial Inc.",          nameKo: "프루덴셜파이낸셜" },
  { symbol: "MET",   name: "MetLife Inc.",                       nameKo: "메트라이프" },
  { symbol: "PGR",   name: "Progressive Corp.",                  nameKo: "프로그레시브" },
  { symbol: "ALL",   name: "Allstate Corp.",                     nameKo: "올스테이트" },
  { symbol: "TRV",   name: "Travelers Companies Inc.",           nameKo: "트래블러스" },
  { symbol: "HIG",   name: "Hartford Financial Services Group",  nameKo: "하트포드" },
  { symbol: "ICE",   name: "Intercontinental Exchange Inc.",     nameKo: "인터컨티넨탈익스체인지" },
  { symbol: "MSCI",  name: "MSCI Inc.",                          nameKo: "MSCI" },
  { symbol: "FI",    name: "Fiserv Inc.",                        nameKo: "파이서브" },
  { symbol: "GPN",   name: "Global Payments Inc.",               nameKo: "글로벌페이먼츠" },
  { symbol: "ALLY",  name: "Ally Financial Inc.",                nameKo: "얼라이파이낸셜" },
  { symbol: "SYF",   name: "Synchrony Financial",                nameKo: "싱크로니파이낸셜" },

  // ── 산업재/물류 ─────────────────────────────────────────────────
  { symbol: "UNP",   name: "Union Pacific Corp.",                nameKo: "유니언퍼시픽" },
  { symbol: "CSX",   name: "CSX Corp.",                          nameKo: "CSX" },
  { symbol: "NSC",   name: "Norfolk Southern Corp.",             nameKo: "노포크서던" },
  { symbol: "WM",    name: "Waste Management Inc.",              nameKo: "웨이스트매니지먼트" },
  { symbol: "RSG",   name: "Republic Services Inc.",             nameKo: "리퍼블릭서비스" },
  { symbol: "FAST",  name: "Fastenal Co.",                       nameKo: "패스트널" },
  { symbol: "GWW",   name: "W.W. Grainger Inc.",                 nameKo: "그레인저" },
  { symbol: "PWR",   name: "Quanta Services Inc.",               nameKo: "퀀타서비스" },
  { symbol: "CARR",  name: "Carrier Global Corp.",               nameKo: "캐리어글로벌" },
  { symbol: "OTIS",  name: "Otis Worldwide Corp.",               nameKo: "오티스월드와이드" },
  { symbol: "ITW",   name: "Illinois Tool Works Inc.",           nameKo: "일리노이툴웍스" },
  { symbol: "PH",    name: "Parker-Hannifin Corp.",              nameKo: "파커하니핀" },
  { symbol: "ROK",   name: "Rockwell Automation Inc.",           nameKo: "록웰오토메이션" },

  // ── 헬스케어 ────────────────────────────────────────────────────
  { symbol: "EW",    name: "Edwards Lifesciences Corp.",         nameKo: "에드워즈라이프사이언스" },
  { symbol: "ZTS",   name: "Zoetis Inc.",                        nameKo: "조에티스" },
  { symbol: "ELV",   name: "Elevance Health Inc.",               nameKo: "엘리번스헬스" },
  { symbol: "HUM",   name: "Humana Inc.",                        nameKo: "휴마나" },
  { symbol: "MOH",   name: "Molina Healthcare Inc.",             nameKo: "몰리나헬스케어" },
  { symbol: "CNC",   name: "Centene Corp.",                      nameKo: "센텐" },

  // ── 소비재/유통/리테일 ──────────────────────────────────────────
  { symbol: "TJX",   name: "TJX Companies Inc.",                 nameKo: "TJX컴퍼니즈" },
  { symbol: "ROST",  name: "Ross Stores Inc.",                   nameKo: "로스스토어즈" },
  { symbol: "DLTR",  name: "Dollar Tree Inc.",                   nameKo: "달러트리" },
  { symbol: "KR",    name: "Kroger Co.",                         nameKo: "크로거" },
  { symbol: "VFC",   name: "V.F. Corp.",                         nameKo: "VF코퍼레이션" },
  { symbol: "HSY",   name: "Hershey Co.",                        nameKo: "허쉬" },
  { symbol: "MNST",  name: "Monster Beverage Corp.",             nameKo: "몬스터베버리지" },
  { symbol: "EL",    name: "Estee Lauder Companies Inc.",        nameKo: "에스티로더" },
  { symbol: "ULTA",  name: "Ulta Beauty Inc.",                   nameKo: "울타뷰티" },
  { symbol: "BBWI",  name: "Bath & Body Works Inc.",             nameKo: "배스앤바디웍스" },
  { symbol: "CL",    name: "Colgate-Palmolive Co.",              nameKo: "콜게이트-팜올리브" },
  { symbol: "KMB",   name: "Kimberly-Clark Corp.",               nameKo: "킴벌리클라크" },
  { symbol: "CHD",   name: "Church & Dwight Co.",                nameKo: "처치앤드와이트" },

  // ── 반도체/하드웨어 추가 ─────────────────────────────────────────
  { symbol: "SWKS",  name: "Skyworks Solutions Inc.",            nameKo: "스카이웍스솔루션즈" },
  { symbol: "QRVO",  name: "Qorvo Inc.",                         nameKo: "코르보" },
  { symbol: "ADI",   name: "Analog Devices Inc.",                nameKo: "아날로그디바이시스" },
  { symbol: "ONTO",  name: "Onto Innovation Inc.",               nameKo: "온토이노베이션" },
  { symbol: "WOLF",  name: "Wolfspeed Inc.",                     nameKo: "울프스피드" },
  { symbol: "PI",    name: "Impinj Inc.",                        nameKo: "임핀지" },
  { symbol: "ACLS",  name: "Axcelis Technologies Inc.",          nameKo: "액셀리스테크놀로지즈" },
  { symbol: "COHU",  name: "Cohu Inc.",                          nameKo: "코후" },

  // ── 클라우드/엔터프라이즈 SaaS 추가 ─────────────────────────────
  { symbol: "ANSS",  name: "Ansys Inc.",                         nameKo: "안시스" },
  { symbol: "U",     name: "Unity Software Inc.",                nameKo: "유니티소프트웨어" },
  { symbol: "TWLO",  name: "Twilio Inc.",                        nameKo: "트윌리오" },
  { symbol: "FIVN",  name: "Five9 Inc.",                         nameKo: "파이브나인" },
  { symbol: "NICE",  name: "NICE Ltd. (ADR)",                    nameKo: "나이스시스템즈" },
  { symbol: "ASAN",  name: "Asana Inc.",                         nameKo: "아사나" },
  { symbol: "BOX",   name: "Box Inc.",                           nameKo: "박스" },
  { symbol: "DBX",   name: "Dropbox Inc.",                       nameKo: "드롭박스" },
  { symbol: "DOCN",  name: "DigitalOcean Holdings Inc.",         nameKo: "디지털오션" },
  { symbol: "FSLY",  name: "Fastly Inc.",                        nameKo: "패스틀리" },
  { symbol: "DT",    name: "Dynatrace Inc.",                     nameKo: "다이나트레이스" },
  { symbol: "NEWR",  name: "New Relic Inc.",                     nameKo: "뉴렐릭" },
  { symbol: "SUMO",  name: "Sumo Logic Inc.",                    nameKo: "수모로직" },
  { symbol: "ALTR",  name: "Altair Engineering Inc.",            nameKo: "알테어엔지니어링" },
  { symbol: "APPN",  name: "Appian Corp.",                       nameKo: "애피안" },
  { symbol: "NCNO",  name: "nCino Inc.",                         nameKo: "엔사이노" },
  { symbol: "PAYA",  name: "Paya Holdings Inc.",                 nameKo: "파야홀딩스" },

  // ── 미디어/엔터 ────────────────────────────────────────────────
  { symbol: "FOX",   name: "Fox Corp. Class B",                  nameKo: "폭스코퍼레이션" },
  { symbol: "FOXA",  name: "Fox Corp. Class A",                  nameKo: "폭스코퍼레이션A" },
  { symbol: "IMAX",  name: "IMAX Corp.",                         nameKo: "아이맥스" },

  // ── 헬스케어 기기/진단 ──────────────────────────────────────────
  { symbol: "A",     name: "Agilent Technologies Inc.",          nameKo: "애질런트테크놀로지즈" },
  { symbol: "IQV",   name: "IQVIA Holdings Inc.",                nameKo: "IQ비아홀딩스" },
  { symbol: "CRL",   name: "Charles River Laboratories International Inc.", nameKo: "찰스리버래보러토리즈" },
  { symbol: "MTD",   name: "Mettler-Toledo International Inc.",  nameKo: "메틀러-톨레도" },
  { symbol: "BIO",   name: "Bio-Rad Laboratories Inc.",          nameKo: "바이오래드" },
  { symbol: "PODD",  name: "Insulet Corp.",                      nameKo: "인슐렛" },
  { symbol: "TNDM",  name: "Tandem Diabetes Care Inc.",          nameKo: "탠덤다이어베티스케어" },

  // ── 여행/숙박 ──────────────────────────────────────────────────
  { symbol: "WH",    name: "Wyndham Hotels & Resorts Inc.",      nameKo: "윈덤호텔앤리조트" },
];
