-- 장중 실시간 시황방 (US/KR) — 익명 메시지
create table if not exists public.session_chat_messages (
  id bigint generated by default as identity primary key,
  market text not null check (market in ('us', 'kr')),
  user_id text not null,
  nickname text not null,
  content text not null check (char_length(content) between 2 and 200),
  created_at timestamptz not null default now()
);

create index if not exists session_chat_messages_market_created_idx
  on public.session_chat_messages (market, created_at desc);

alter table public.session_chat_messages enable row level security;
revoke all on table public.session_chat_messages from anon, authenticated;
grant all on table public.session_chat_messages to service_role;
